# 第十二章 通过异常处理错误

目的在于通过使用少于目前数量的代码来简化大型、可靠的程序的生成，使得应用中没有未处理的错误

### 12.1 概念

### 12.2 基本异常

抛出异常后：

1. 将使用new在堆上创建异常对象
2. 当前执行路径被终止，从当前环境中弹出对异常对象的引用
3. 从异常处理程序继续执行

##### 12.2.1 异常参数

用new创建异常对象伴随着存储空间的分配和构造器的调用。标准异常类有两个构造器：默认构造器和接受字符串作为参数以放入异常对象的构造器

能够抛出任意类型的Throwable对象，它是异常类型的根类

### 12.3 捕获异常

监控区域：一段可能产生异常的代码，后面跟着处理这些异常的代码

##### 12.3.1 try块

##### 12.3.2 异常处理程序

每个catch子句接受一个且仅接受一个特殊类型的参数

终止模型：一旦异常被抛出，就表明错误无法挽回，不能回来继续执行

恢复模型：修正错误，然后重新尝试调用出问题的方法。（两种方式：不抛出异常，调用方法修正错误；把try块放进while循环，直到得到满意的结果）不够实用，会导致耦合。

### 12.4 创建自定义异常

printStackTrace()方法将打印从方法调用处直到异常抛出处的方法调用序列，信息将被输出到标准错误流

##### 12.4.1 异常与记录日志

```java
import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.logging.Logger;

class LoggingException extends Exception {
    private static Logger logger = Logger.getLogger("LoggingException");
    public LoggingException() {
        StringWriter trace = new StringWriter();
        printStackTrace(new PrintWriter(trace));
        logger.severe(trace.toString());
    }
}

public class LoggingExceptions {
    public static void main(String[] args) {
        try {
            throw new LoggingException();
        } catch (LoggingException e) {
            System.err.println("Caught " + e);
        }
        try {
            throw new LoggingException();
        } catch (LoggingException e) {
            System.err.println("Caught " + e);
        }
    }
}
```

### 12.5 异常说明

告知客户端程序员某个方法可能会抛出的异常类型，然后客户端程序员就可以进行相应的处理，如：

void f() throws TooBig, Too Small, {...}

代码必须与异常说明保持一致

### 12.6 捕获所有异常

##### 12.6.1 栈轨迹

```java
public class WhoCalled {
    static void f() {
        try {
            throw new Exception();
        } catch (Exception e) {
            for (StackTraceElement ste: e.getStackTrace())
                System.out.println(ste.getMethodName());
        }
    }
    static void g() { f(); }
    static void h() { g(); }

    public static void main(String[] args) {
        f();
        System.out.println("----------------------");
        g();
        System.out.println("----------------------");
        h();
    }
}
```

getStackTrace()将返回一个由栈轨迹中的元素所构成的数组，每一个元素都表示栈中的一帧

##### 12.6.2 重新抛出异常

##### 12.6.3 异常链

捕获一个异常后抛出另一个异常且希望把原始异常的信息保存下来，这被称为异常链

所有Throwable的子类在构造器中都可以接受一个cause对象作为参数用来表示原始异常，再把其传递给新异常

只有三种基本的异常类提供了带cause参数的构造器：Error、Exception、RuntimeException。其它类型的异常应用initCause()方法而不是构造器

```java
class DynamicFieldsException extends Exception {}

public class DynamicFields {
    private Object[][] fields;
    public DynamicFields(int initialSize) {
        fields = new Object[initialSize][2];
        for (int i = 0; i < initialSize; i++) {
            fields[i] = new Object[] {null, null};
        }
    }
    public String toString() {
        StringBuilder result = new StringBuilder();
        for (Object[] obj: fields) {
            result.append(obj[0]);
            result.append(": ");
            result.append(obj[1]);
            result.append("\n");
        }
        return result.toString();
    }
    private int hasField(String id) {
        for (int i = 0; i < fields.length; i++) {
            if(id.equals(fields[i][0]))
                return i;
        }
        return -1;
    }
    private int getFieldNumber(String id) throws NoSuchFieldException {
        int fieldNum = hasField(id);
        if(fieldNum == -1)
            throw new NoSuchFieldException();
        return fieldNum;
    }
    private int makeField(String id) {
        for (int i = 0; i < fields.length; i++)
            if (fields[i][0] == null) {
                fields[i][0] = id;
                return i;
            }
        //no empty fields, add one:
        Object[][] temp = new Object[fields.length + 1][2];
        for (int i = 0; i < fields.length; i++) {
            temp[i] = fields[i];
        }
        for (int i = fields.length; i < temp.length; i++)
            temp[i] = new Object[] {null, null};
        fields = temp;
        //recursive call with expanded fields
        return makeField(id);
    }
    public Object getField(String id) throws NoSuchFieldException {
        return fields[getFieldNumber(id)][1];
    }
    public Object setField(String id, Object value) throws DynamicFieldsException {
        if(value == null) {
            DynamicFieldsException dfe = new DynamicFieldsException();
            dfe.initCause(new NullPointerException());
            throw dfe;
        }
        int fieldNumber = hasField(id);
        if(fieldNumber == -1)
            fieldNumber = makeField(id);
        Object result = null;
        try {
            result = getField(id);
        } catch (NoSuchFieldException e) {
            throw new RuntimeException(e);
        }
        fields[fieldNumber][1] = value;
        return result;
    }

    public static void main(String[] args) {
        DynamicFields df = new DynamicFields(3);
        System.out.println(df);
        try {
            df.setField("d", "A value for d");
            df.setField("number", 47);
            df.setField("number2", 48);
            System.out.println(df);
            df.setField("d", "A new value for d");
            df.setField("number3", 11);
            System.out.println("df: " + df);
            System.out.println("df.getField(\"d\") : " + df.getField("d"));
            Object field = df.setField("d", null);
        } catch (NoSuchFieldException e) {
            e.printStackTrace(System.out);
        } catch (DynamicFieldsException e) {
            e.printStackTrace(System.out);
        }
    }
}
```

在运行时动态地向DynamicFields对象添加字段，若试图为字段设置一个空值，将抛出一个DynamicFieldsException异常，它是通过使用initCause()方法把NullPointerException对象插入而建立的

如果异常是从setField()方法里抛出应视为编程错误，所以就用接受cause参数的构造器把NoSuchFieldException异常转换为RuntimeException异常

### 12.7 Java标准异常

Throwable这个类被用来表示任何可以作为异常被抛出的类，可分为两种：Error，Exception

##### 12.7.1 特例：RuntimeException

属于运行时异常的类型有很多，它们会自动被虚拟机抛出所以不必在异常说明中列出来。它们都是从RuntimeException类继承而来。

只能在代码中忽略RuntimeException及其子类的异常。因为其代表的是编程错误

### 12.8 使用finally进行清理

无论异常是否被抛出，finally子句总能被执行

##### 12.8.1 finally用来做什么

使用场景：当要把除内存之外的资源恢复到它们的初始状态时，就要用finally子句。这种需要清理的资源包括：已经打开的文件或网络连接，在屏幕上画的图形，甚至可以是外部世界的某个开关。如：

```java
public class Switch {
    private boolean state = false;
    public boolean read() {
        return state;
    }
    public void on() {
        state = true;
        System.out.println(this);
    }
    public void off() {
        state = false;
        System.out.println(this);
    }
    public String toString() {
        return state ? "on" : "off";
    }
}

class OnOffException1 extends Exception {}

class OnOffException2 extends Exception {}

class OnOffSwitch {
    private static Switch sw = new Switch();
    public static void f() throws OnOffException1, OnOffException2 {}

    public static void main(String[] args) {
        try {
            sw.on();
            f();
            sw.off();
        } catch (OnOffException1 e) {
            System.out.println("OnOffException1");
            sw.off();
        } catch (OnOffException2 e) {
            System.out.println("OnOffException2");
            sw.off();
        }
    }
}
```

在每个try块和异常处理程序的末尾都加入sw.off()确保开关在main()结束时关闭，但在异常抛出没被处理程序捕获时该方法就得不到调用了，此时应用finally，改成如下

```java
	public static void main(String[] args) {
        try {
            sw.on();
            f();
        } catch (OnOffException1 e) {
            System.out.println("OnOffException1");
        } catch (OnOffException2 e) {
            System.out.println("OnOffException2");
        } finally {
            sw.off();
        }
    }
```

涉及break和continue语句的时候，finally子句也会得到执行

##### 12.8.2 在return中使用finally

##### 12.8.3 缺憾：异常丢失

### 12.9 异常的限制

当覆盖方法的时候，只能抛出在基类方法的异常说明中列出的那些异常

### 12.10 构造器

对于在构造阶段可能会抛出异常并且要求清理的类，最安全的使用方式是使用嵌套的try子句

通用的清理基本规则：在创建需要清理的对象之后，立即进入一个try-finally语句块，如：

```java
class NeedsCleanup { // Construction can't fail
  private static long counter = 1;
  private final long id = counter++;
  public void dispose() {
    System.out.println("NeedsCleanup " + id + " disposed");
  }
}

class ConstructionException extends Exception {}

class NeedsCleanup2 extends NeedsCleanup {
  // Construction can fail:
  public NeedsCleanup2() throws ConstructionException {}
}

public class CleanupIdiom {
  public static void main(String[] args) {
    // Section 1:
    NeedsCleanup nc1 = new NeedsCleanup();
    try {
      // ...
    } finally {
      nc1.dispose();
    }

    // Section 2:
    // If construction cannot fail you can group objects:
    NeedsCleanup nc2 = new NeedsCleanup();
    NeedsCleanup nc3 = new NeedsCleanup();
    try {
      // ...
    } finally {
      nc3.dispose(); // Reverse order of construction
      nc2.dispose();
    }

    // Section 3:
    // If construction can fail you must guard each one:
    try {
      NeedsCleanup2 nc4 = new NeedsCleanup2();
      try {
        NeedsCleanup2 nc5 = new NeedsCleanup2();
        try {
          // ...
        } finally {
          nc5.dispose();
        }
      } catch(ConstructionException e) { // nc5 constructor
        System.out.println(e);
      } finally {
        nc4.dispose();
      }
    } catch(ConstructionException e) { // nc4 constructor
      System.out.println(e);
    }
  }
}
Output:
NeedsCleanup 1 disposed
NeedsCleanup 3 disposed
NeedsCleanup 2 disposed
NeedsCleanup 5 disposed
NeedsCleanup 4 disposed
```

### 12.11 异常匹配

抛出异常时，异常处理系统会按照代码书写顺序找出最近的处理程序，找到后就不再继续查找。查找时并不要求抛出的异常同处理程序所声明的异常完全匹配，派生类的对象也可以匹配其基类的处理程序。

把捕获异常基类的语句放在后面，否则会屏蔽掉派生类的异常。

### 12.12 其他可选方式

减少编译时施加的约束能显著提高程序员的编程效率

### 12.13 异常使用指南

应该在下列情况使用异常：

1. 在恰当的级别处理问题。（在知道该如何处理的时候才捕获异常）
2. 解决问题并且重新调用产生异常的方法
3. 进行少许修补，然后绕过异常发生的地方继续执行
4. 用别的数据进行计算，以代替方法预计会返回的值
5. 把当前运行环境下能做的事尽量做完，然后把**相同**的异常重抛到更高层
6. 把当前运行环境下能做的事尽量做完，然后把**不同**的异常抛到更高层
7. 终止程序
8. 进行简化
9. 让类库和程序更安全